### ISSUE TITLE
Azure Express Route Configuration / Modification

### ISSUE THREAD

**Issue by AErmie** [bcgov/Cloud-Pathfinder-Azure#114]
Currently, Azure Express Route is deployed and implemented using the [Azure landing zones Terraform module](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale).

We need to research and test what is and is not supported through the CAF Terraform module, in particular VPN Gateway, Circuits, Site Connections, etc.

> [!NOTE]
> From initial investigation and research, although the Azure Terraform CAF Enterprise Scale module creates a base Azure Express Route VPN Gateway, it does not support the lower-level resources, such as Circuits, Gateway Connections, etc.
>
> There currently is no Azure Verified Module for theses resource (though there are "proposed" modules). This means we will need to create our own modules, that will reference/use existing resources (via a `data {}` reference, etc.)
>
> The challenge we may encounter is a conflict of resource ownership between the CAF and our own custom modules whenever we run the various pipelines.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Testing support for lower-level resources in Azure Express Route**
  - Given the current implementation of the Azure landing zones Terraform module
  - When testing the support for lower-level resources like VPN Gateway, Circuits, Site Connections, etc.
  - Then we should identify what is and is not supported through the CAF Terraform module
- [ ] **Scenario: Investigate Azure Verified Module availability**
  - Given the current implementation of the Azure landing zones Terraform module
  - When researching the availability of an Azure Verified Module for lower-level resources in Azure Express Route
  - Then we should identify if there are any existing modules or proposed modules that can be used
- [ ] **Scenario: Create custom modules for unsupported resources**
  - Given the current implementation of the Azure landing zones Terraform module
  - When creating custom modules to support lower-level resources in Azure Express Route
  - Then we should ensure these custom modules reference/use existing resources via `data {}` references
- [ ] **Scenario: Address potential conflicts between CAF and custom modules**
  - Given the current implementation of the Azure landing zones Terraform module
  - When running various pipelines with both CAF and custom modules for lower-level resources in Azure Express Route
  - Then we should identify and address any potential conflicts in resource ownership

**Comment by AErmie** [comment]
Preliminary Terraform code created and partially tested, available in the [azure-lz-terraform-modules](https://github.com/bcgov/azure-lz-terraform-modules) repo.

## What's Been Tested:
- Express Route circuit creation
- Express Route circuit peering (**AzurePrivatePeering** specifically)
- Express Route connection
  - Tested `terraform plan`, and executed `terraform apply` though `apply` failed (as expected) because the VPN Gateway is not deployed yet

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekcvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--122ff34c953d3ccf31bf79aecea365fc793901ed/image.png" alt="image.png" />

<img width="1578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeksvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e570dd5a1a218a812cedc81b9aa324646e97021b/image.png" alt="image.png" />

> [!NOTE]
> While performing `terraform destroy` to clean up the resources, the delete operation stepped on itself (ie. trying to delete the Circuit before/during the deletion of the Peering). This may be due to how each component is separated into its own module deployment.

**Comment by wrnu** [comment]
Complete
