### ISSUE TITLE
Create document (Loop) to track customer questions (FAQs), feedback, to build onboading guide

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#120]
- [ ] Create a document in the Loop Public Cloud Workspace
- [ ] Organize sections for Feedback, Questions (FAQs - track who asked the questions), and Suggested onboarding items
- [ ] Tell Azure team members about it and start entering already existing content (from fist tester team).

**Comment by abibat-adesina** [comment]
[loop](https://loop.cloud.microsoft/p/eyJ3Ijp7InUiOiJodHRwczovL2JjZ292LnNoYXJlcG9pbnQuY29tLz9uYXY9Y3owbE1rWW1aRDFpSVRsd1Z6Sm1Wa0pEV1VVdFZuTnpjWEZXZWpWcWNGVjZTMFJoYzJsZmNHeFFhRE13TlhKMGRXYzNUMlF5V2t3M2FGTkhTVmxSY21KcFdqaHFUMGRFY1hrbVpqMHdNVlZQU2tGUE5FazJOMDlLVERWYVJFWlNOVWRMUkVoVFV6TTJVMU15VVZKWEptTTlKbVpzZFdsa1BURSUzRCIsInIiOmZhbHNlfSwicCI6eyJ1IjoiaHR0cHM6Ly9iY2dvdi5zaGFyZXBvaW50LmNvbS86Zmw6L3IvY29udGVudHN0b3JhZ2UvQ1NQXzdkYjY5NWY2LTQyNTAtNGY2MC05NWIyLWNhYWE1NzNlNjNhNS9Eb2N1bWVudCUyMExpYnJhcnkvTG9vcEFwcERhdGEvVW50aXRsZWQubG9vcD9kPXcxY2RjYzUxZmU2ODg0ZDA5YjQ2M2M3MDc4OTQ4YzEwOSZjc2Y9MSZ3ZWI9MSZuYXY9Y3owbE1rWmpiMjUwWlc1MGMzUnZjbUZuWlNVeVJrTlRVRjgzWkdJMk9UVm1OaTAwTWpVd0xUUm1OakF0T1RWaU1pMWpZV0ZoTlRjelpUWXpZVFVtWkQxaUlUbHdWekptVmtKRFdVVXRWbk56Y1hGV2VqVnFjRlY2UzBSaGMybGZjR3hRYURNd05YSjBkV2MzVDJReVdrdzNhRk5IU1ZsUmNtSnBXamhxVDBkRWNYa21aajB3TVZWUFNrRlBORWszV1ZoUFFscERTRWRDUmtjelNWazJTRUUyUlZWU1VVbEtKbU05SlRKR0ptWnNkV2xrUFRFbVlUMU1iMjl3UVhCd0puQTlKVFF3Wm14MWFXUjRKVEpHYkc5dmNDMXdZV2RsTFdOdmJuUmhhVzVsY2laNFBTVTNRaVV5TW5jbE1qSWxNMEVsTWpKVU1GSlVWVWg0YVZreVpIWmthVFY2WVVkR2VWcFlRblpoVnpVd1RHMU9kbUpZZUdsSlZHeDNWbnBLYlZaclNrUlhWVlYwVm01T2VtTllSbGRsYWxaeFkwWldObE13VW1oak1teG1ZMGQ0VVdGRVRYZE9XRW93WkZkak0xUXlVWGxYYTNjellVWk9TRk5XYkZKamJVcHdWMnBvY1ZRd1pFVmpXR3c0VFVSR1ZsUXdjRUpVZWxKS1RtcGtVRk5yZHpGWGExSkhWV3BXU0ZNd1VrbFZNVTE2VG14T1ZFMXNSbE5XZHlVelJDVXpSQ1V5TWlVeVF5VXlNbWtsTWpJbE0wRWxNakkxT1RnMU5qVXhOQzB4T0dVMUxUUmhZek10T1RSbU9DMDNabU0xWVdVNE56TTNNV0VsTWpJbE4wUSUzRCIsInIiOmZhbHNlfSwiaSI6eyJpIjoiNTk4NTY1MTQtMThlNS00YWMzLTk0ZjgtN2ZjNWFlODczNzFhIn19)
