### ISSUE TITLE
Microsoft Unified Support

### ISSUE THREAD

**Issue by abibat-adesina** [bcgov/Cloud-Pathfinder-Azure#123]
- [x] Create a simplified document about the Microsoft Unified support
- [x] Check the doc with Pilar
- [ ] Olena approves the doc
- [ ] Post doc on IDIR protected PO website

**Comment by ThibaultBC** [comment]
https://app.zenhub.com/workspaces/cloud-pathfinder---ms-azure-651ef5573781d401e78e269d/issues/gh/bcgov/cloud-pathfinder-azure/129

**Comment by ThibaultBC** [comment]
@abibat-adesina to add content. Working with Pilar

**Comment by ThibaultBC** [comment]
This content has already be done (cf. Olena)
