### ISSUE TITLE
New Project Set Onboarding Process Documentation

### ISSUE THREAD

**Issue by AErmie** [bcgov/Cloud-Pathfinder-Azure#129]
As part of onboarding a new Project Set, we need to create a Standard Operating Procedure (SOP) that includes the following:

- Inform Microsoft about the new Subscription IDs, to add the subscriptions to the Microsoft Unified (Premier Support) Plan
  - This is required so that Product Owners (POs), and Technical Leads (TLs), are empowered to open Support Cases as needed

> [!NOTE]
> We should also look into how we can automate some of this process. Currently, it requires someone emailing our Microsoft Technical Account Manager (TAM) with a list of Subscription IDs.
> 
> Even though Microsoft's process itself is not automated either, could we programmatically collect the new Subscription IDs and send an automated email on a weekly basis?

## Acceptance Criteria

 - [ ] **Scenario: New Project Set Onboarding Process Documentation**
  - Given the SOP for onboarding a new Project Set is created
  - When the SOP includes information about informing Microsoft about Subscription IDs and adding subscriptions to the Microsoft Unified (Premier Support) Plan
  - Then the POs and TLs can open Support Cases as needed
 - [ ] **Scenario: Automation of collecting Subscription IDs**
  - Given a programmatic way to collect new Subscription IDs is implemented
  - When an automated email is sent on a weekly basis with the collected Subscription IDs
  - Then it helps in streamlining the process and reduces manual effort

**Comment by AErmie** [comment]
There is a [Subscriptions Get](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/get?view=rest-resources-2022-12-01&tabs=HTTP) API, but it does not have any relevant information about associated Support Plan. Additionally, there is a [Microsoft Azure CLI 'support' Extension](https://github.com/Azure/azure-cli-extensions/tree/main/src/support), but again, it does not have any properties that would show the type of Support Plan available.

**Comment by wrnu** [comment]
I think the Unified support makes this all a bit strange. We should put this on our list of things to talk with Barry about

**Comment by mitovskaol** [comment]
@abibat-adesina @AErmie Please make sure the Azure tech docs are close as possible to the AWS tech docs i.e. have the same structure and same content just Azure specific. Also, please avoid copy-pasting content from the vendor website, just include the link.

**Comment by AErmie** [comment]
As part of onboarding a new Project Set, our documentation states:

> Once approved, your Project Set will be provisioned, followed up by an email sent to the Product Owner and Technical Lead(s) once the provisioning is complete.

This part of the process is (or should be) automated. This means we could modify this process to also email Microsoft with the new Subscription IDs to enable for Unified Support.

**Comment by wrnu** [comment]
We'll lie with the current system where Bhaskar monitors for new subs
