### ISSUE TITLE
Prevent Public Network Access for Specific Azure PaaS Services

### ISSUE THREAD

**Issue by AErmie** [bcgov/Cloud-Pathfinder-Azure#144]
After applying the **Configure Azure PaaS services to use private DNS zones** and **Deny the creation of private DNS** policies in the environment, we need to decide which Azure PaaS services should be prevented from having public network access (ie. Storage Accounts, CosmosDB, Key Vault, etc.).

We need to explore what customizations are possible in the **Public network access should be disabled for PaaS services** policy, so that we don't prevent all Azure PaaS services, but a specific subset.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario: Explore customizations in the Public network access policy**
  - Given the environment has a customized "Public network access should be disabled for PaaS services" policy
  - When selecting which Azure PaaS services should be prevented from having public network access
  - Then only the specified Azure PaaS services (e.g., Storage Accounts, CosmosDB, Key Vault) should have their public network access disabled

**Comment by AErmie** [comment]
The following Azure PaaS services are currently part of the built-in **Public network access should be disabled for PaaS services** policy initiative:

**Application Elements:**
- API Management
- App Configurations
- App Services
- App Service Environments
- Function apps

 **AI / Machine Learning:**
- Azure Bot service
- Azure Machine Learning workspaces

**Containers:**
- Azure Kubernetes Service (Private Cluster)
- Container registries

**Databases:**
- Azure Cache for Redis
- Azure SQL Database
- CosmosDB
- MariaDB servers
- MySQL Flexible Servers
- PostgreSQL Flexible Servers

**Storage:**
- Storage Accounts
- Azure File Sync

**Other:**
- Automation accounts
- Batch accounts
- Key Vault

**Comment by wrnu** [comment]
Only apply to the Landing zones MG

**Comment by AErmie** [comment]
After discussion with the team, we've decided to only prevent public IP addresses for the following Azure PaaS resources:
- Azure Cache for Redis
- Azure SQL Database
- CosmosDB
- MariaDB servers
- MySQL Flexible Servers
- PostgreSQL Flexible Servers
- Key Vault

The **Public network access should be disabled for PaaS services** policy initiative was successfully assigned to the Landing Zone Management Group level, with custom parameters.

The custom parameters set the "*PublicIpDenyEffect" to `Disabled` for all listed resources, with the exception of the above mentioned resources (which are set to `Deny`).

Testing of this policy was successful, where the creation of a resource (from the Deny list), successfully was prevented:

<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c91b1695ed931a0a968d2b4df5e91d05d657d818/image.png" alt="image.png" />
