### ISSUE TITLE
Azure Networking Documentation and Architecture Diagram

### ISSUE THREAD

**Issue by wrnu** [bcgov/Cloud-Pathfinder-Azure#147]
In preparation for the setup/configuration of Express Route, we need to document the current Azure networking, and diagram inter-dependencies, with a specific focus on Express Route related components.

The main purpose for this is to communicate and coordinate with the Hosting Network team, in preparation for the on-premises components and connectivity.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Documentation of Azure networking**
  - Given a clear and detailed documentation of current Azure networking
  - When the documentation is reviewed by the Hosting Network team
  - Then the team should have a clear understanding of the network architecture, including Express Route related components
 - [ ] **Scenario: Interdependencies diagram for Azure networking**
  - Given an interdependencies diagram that shows relationships between all components
  - When the diagram is shared with the Hosting Network team
  - Then the team should have a clear visual representation of how everything fits together, including Express Route related components

**Comment by AErmie** [comment]
Sample architecture diagram

<img width="1691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDM2Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c37a31a309736f1b946c4585381281ac0d70d32a/image.png" alt="image.png" />

Source: https://bcgov.sharepoint.com/:u:/r/teams/01368-CPFScrumTeam/Shared%20Documents/CPF%20Scrum%20Team/007%20-%20Documentation%20%26%20Research/Azure%20LZ/Azure%20ExpressRoute.drawio?csf=1&web=1&e=hldd4d

**Comment by AErmie** [comment]
The short-form of what we need for Express Route is:

1. Create [Express Route VPN Gateway](https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-add-gateway-portal-resource-manager)
2. Create [Express Route Circuit](https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-circuit-portal-resource-manager)
3. Provide the generated Service Key to our Service Provider (Equinix)
4. Create a [circuit peering](https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-routing-portal-resource-manager) connection to the VPN Gateway

 
## Needed Information

- Resiliency configuration
  - Suggest "Standard" for FORGE, and "Maximum" for LIVE
- Billing model
  - Suggest "Metered" for FORGE, not sure what's been decided for LIVE
- Peering location
- Bandwidth
- 2x /30 subnets
- VLAN ID
- Peer ASN
- Shared Key

 
## Note
It seems that Equinix is only supported when using Standard or Maximum resiliency configuration (not "High" resiliency)

**Comment by AErmie** [comment]
High-level documentation for collaboration with the Hosting team, has been created here: [Azure Platform Networking](https://bcgov.sharepoint.com/:w:/r/teams/01368-CPFScrumTeam/Shared%20Documents/CPF%20Scrum%20Team/007%20-%20Documentation%20%26%20Research/Azure%20LZ/Azure%20Platform%20Networking.docx?d=wb2d5ce0e254b4314bd0d9b2b51c5cb8e&csf=1&web=1&e=fWqq9L).
