### ISSUE TITLE
Tech Doc - User management how-to

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#148]
- [x] Warren to write content
- [ ] Abi to help publishing in Backstage

**Comment by wrnu** [comment]
Added to the PR @abibat-adesina made for the Azure docs structure 

https://github.com/bcgov/public-cloud-techdocs/pull/48

https://github.com/bcgov/public-cloud-techdocs/blob/azure-placeholder/docs%2Fazure%2Fdesign-build-and-deploy-an-application%2Fuser-management.md
