### ISSUE TITLE
Schedule early adopters check-ins

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#152]
1. Schedule 15-min individual check-ins with early adopter teams that have provisioned a project in Azure

Check-in agenda:
- How did the onboarding go so far?
- Discussing the current stage of their project in Azure
- Any issues, blockers

2. Make it recurring weekly for 4 weeks

**Comment by abibat-adesina** [comment]
We have checked-in with 4 teams so far and meeting scheduled with the remaining teams
