### ISSUE TITLE
Research / Investigate Using CosmosDB Data Explorer without Public Internet Access

### ISSUE THREAD

**Issue by AErmie** [bcgov/Cloud-Pathfinder-Azure#160]
We have an Azure Policy in place, that prevents databases being created with any public Internet access. Therefore a Private Endpoint is required.

However, when this is configured (in particular the Networking > Public Access is disabled)...

<img width="828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b30b9e3866ed44dc4c8aa3675afa5967177902f1/image.png" alt="image.png" />

... then the [Data Explorer](https://learn.microsoft.com/en-us/azure/cosmos-db/data-explorer) feature displays the following error in the portal:

> The Network settings for this account are preventing access from Data Explorer. Please **enable public access** to proceed.

<img width="708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebf3ef698af501463bef46e939883a6852bf114a/image.png" alt="image.png" />

In theory, if you access the Azure portal through a Virtual Machine within the same VNet as the Private Endpoint, you should be able to see/use Data Explorer. However, some users have reported that the same error is still displayed.

Research/investigation needs to be conducted, and Microsoft potentially engaged.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Research on CosmosDB Data Explorer without Public Internet Access**
  - Given a GraphQL mutation is implemented
  - When the mutation is called with input parameters
  - Then the mutation should return the acceptance criteria for using CosmosDB Data Explorer without public internet access

**Comment by wrnu** [comment]
It turns out this does work when accessing the portal from a VM in the private network via Bastion. The portal UI still shows the warning, but it works.
