### ISSUE TITLE
Document billing requirements - cost recovery

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#173]
1. Gather cost recovery requirements
2. List them for next ticket creation

Priority for Q3 - Cost recovery - capturing the spend per team to create JV

Lower priority (Q3-Q4) - billing information / cost and usage monitoring for teams.

Tickets then taken by Adin

**Comment by ThibaultBC** [comment]
No billing emails - create documentation to find billing info directly in Azure

**Comment by wrnu** [comment]
# Cost Recovery System Requirements

## 1\. Overview

This document outlines the requirements for implementing an automated cost recovery system for team expenses using Azure FinOps toolkit and policy-based tagging.

## 2\. Required Report Columns

### 2.1 Primary Data Columns

1. Account Coding (License Plate)  
2. Subtotal (Usage amount in CAD)  
3. GST Amount (5%)  
4. PST Amount (7%)  
5. SSC/Overhead Fee (6%)  
6. Total Amount (Sum of subtotal, taxes, and fees)  
7. Expense Authority Email  
8. Expense Authority Name  
9. Ministry Name

## 3\. Current Process

### 3.1 Quarterly Cost Recovery Workflow

1. Create a spreadsheet with all required columns  
2. Submit spreadsheet to finance team  
3. Finance team creates journal vouchers  
4. Finance team processes cost recovery

## 4\. Technical Requirements

### 4.1 Azure Resource Tagging

#### Mandatory Tags

- Account coding/License plate  
- Billing Group  
- Ministry name

#### Tag Implementation

1. Tags must exist at subscription level  
2. All resources must inherit tags automatically from subscription  
3. Implementation through Azure Policy

### 4.2 Resource Tracking Requirements

1. All costs must be trackable by account coding  
2. Resources must be properly tagged for accurate cost allocation  
3. FinOps toolkit must be configured to track costs by tagged attributes

### 4.3 Reporting Requirements

#### Automated Components

1. Ability to query FinOps toolkit reports by:  
   - Account coding  
   - Time period  
   - Total spend

#### Manual Components

1. Generation of reports including:  
   - Base usage from FinOps toolkit  
   - Tax calculations (GST/PST)  
   - Overhead fee calculations

## 5\. Implementation Steps

1. Configure Azure Policy for automatic tag inheritance  
2. Verify existing subscription-level tags  
3. Implement automatic tagging policy  
4. Set up FinOps toolkit reporting  
5. Create manual reporting process for tax/overhead additions  
6. Validate cost tracking accuracy

## 6\. Success Criteria

1. All resources automatically inherit required tags  
2. Costs are accurately tracked by account coding  
3. Reports can be generated with all required columns  
4. Data can be easily exported for finance team's journal voucher process

## 7\. Stakeholders

- Finance team (Journal voucher processing)  
- Expense Authorities  
- Azure resource owners
