### ISSUE TITLE
Outreach - Phase 2 transition plan

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#177]
1. Draft messaging to announce transition to OCIO Azure Landing Zone to teams in unmanaged space
2. Reach out first to green teams to try and get an early pilot (SAP Hana Transition Project - Digital Office SSO)
3. Organize meeting with teams to discuss particular questions

**Comment by abibat-adesina** [comment]
Communication sent out to teams
