### ISSUE TITLE
List Q&A from Early Adopter Chat

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#179]
There has been some important conversation back and forth in the 🔷🎬Azure Early Access | Kick-off session chat.

- [ ] Review the chat and list relevant questions. Relevant meaning it could be questions asked by other teams.
- [ ] Gather answer provided
- [ ] Gather relevant links share
- [ ] Review for Technical Documentation consideration
- [ ] Add content to Azure FAQ loop component 

https://bcgov.sharepoint.com/:fl:/r/contentstorage/CSP_7db695f6-4250-4f60-95b2-caaa573e63a5/Document%20Library/LoopAppData/Customer%20questions%20(FAQs),%20feedback%20in%20Azure.loop?d=w1cdcc51fe6884d09b463c7078948c109&csf=1&web=1&e=XITOVA&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF83ZGI2OTVmNi00MjUwLTRmNjAtOTViMi1jYWFhNTczZTYzYTUmZD1iITlwVzJmVkJDWUUtVnNzcXFWejVqcFV6S0Rhc2lfcGxQaDMwNXJ0dWc3T2QyWkw3aFNHSVlRcmJpWjhqT0dEcXkmZj0wMVVPSkFPNEk3WVhPQlpDSEdCRkczSVk2SEE2RVVSUUlKJmM9JTJGJmZsdWlkPTEmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4aVkyZHZkaTV6YUdGeVpYQnZhVzUwTG1OdmJYeGlJVGx3VnpKbVZrSkRXVVV0Vm5OemNYRldlalZxY0ZWNlMwUmhjMmxmY0d4UWFETXdOWEowZFdjM1QyUXlXa3czYUZOSFNWbFJjbUpwV2pocVQwZEVjWGw4TURGVlQwcEJUelJKTmpkUFNrdzFXa1JHVWpWSFMwUklVMU16TmxOVE1sRlNWdyUzRCUzRCUyMiUyQyUyMmklMjIlM0ElMjI1OTg1NjUxNC0xOGU1LTRhYzMtOTRmOC03ZmM1YWU4NzM3MWElMjIlN0Q%3D

**Comment by wrnu** [comment]
Ongoing process to integrate feedback into techdocs
