### ISSUE TITLE
Create Firewall Rules for PowerBI On-premises Data Gateway

### ISSUE THREAD

**Issue by ghost** [bcgov/Cloud-Pathfinder-Azure#200]
Based on the following Support Ticket (https://citz-do.atlassian.net/jira/servicedesk/projects/PCS/queues/custom/25/PCS-21), we have determined that a firewall Application Rule should be created, to allow the various domains through.

These will be generalized such as: `*.microsoft.com`, `*.powerbi.com`, `*.windows.net`, etc.

The following list describes the FQDNs used by the gateway. These endpoints are required for the gateway to function: [https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports](https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports)

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlB4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f8e015ce23b5ed745fca6dd9fe95677fa709a09/image.png" alt="image.png" />

This will first be applied in FORGE, and then in LIVE.

**Comment by cwalla-bcgov** [comment]
The following list describes FQDNs used by the gateway. These endpoints are required for the gateway to function:
      
(Source: https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports)

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2Z2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58946be60838d087543892cf2f05507d711f69b7/image.png" alt="image.png" />

**Comment by cwalla-bcgov** [comment]
The following list describes FQDNs used by the gateway. These endpoints are required for the gateway to function:
      
(Source: https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports)

<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2Z2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58946be60838d087543892cf2f05507d711f69b7/image.png" alt="image.png" />

**Comment by wrnu** [comment]
Tracking in Jira

https://citz-do.atlassian.net/browse/PCS-21
