### ISSUE TITLE
Add DNS A-Record to CAF Deployment for PowerBI.com

### ISSUE THREAD

**Issue by AErmie** [bcgov/Cloud-Pathfinder-Azure#206]
Based on the following JIRA ticket ([Unable to Connect to PowerBI.com from Azure VM](https://citz-do.atlassian.net/jira/servicedesk/projects/PCS/queues/custom/25/PCS-21)), and the subsequent solution, we need to add some post-CAF deployment code to create DNS A-Records.

## DNS Records
For PowerBI (and the Data Gateway), we need the following 2 DNS CNAME records in the `privatelink.analysis.windows.net` Private DNS Zone:

```
NAME: app.privatelink.analysis.windows.net
TYPE: CNAME
ALIAS: app-pbi-wfe-canada-central-v3.pbi-wfe-canada-central-v3-ase.p.azurewebsites.net
---
NAME: api.privatelink.analysis.windows.net
TYPE: CNAME
ALIAS: wabi-canada-central-redirect.analysis.windows.net
```

> [!NOTE]
> Ultimately, this is an issue with the CNAME chain from Microsoft for PowerBI.com, specific to Canada.
> The CNAME records are not region dependent.

**Comment by AErmie** [comment]
This is not required if we remove the Private DNS Zone link for PowerBI.

**Comment by wrnu** [comment]
This is no longer be needed once we remove the private dns zone

[Un-Link Analysis Private DNS Zone from Private DNS Resolver VNet](https://app.zenhub.com/workspaces/cloud-pathfinder---ms-azure-651ef5573781d401e78e269d/issues/gh/bcgov/cloud-pathfinder-azure/208)
