### ISSUE TITLE
Project set Terraform module

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#49]
- [x] Create Mgt groups
- [x] Create 4 subscriptions (input configurable)
- [ ] Get network ranges from Ipam

**Comment by wrnu** [comment]
I have decided that it makes more sense to get the network ranges from IPAM in the deployment repo or possibly even the provisioner.

The first draft if the module is complete:

https://github.com/bcgov/terraform-azure-lz-project-set
