### ISSUE TITLE
IPAM - Platform Networking

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#64]
Deploy https://azure.github.io/ipam/#/

**Comment by ThibaultBC** [comment]
Waiting for MS team (Barry) to answer some questions.
+ ADMS request pending.

**Comment by ThibaultBC** [comment]
ADMS - need them to allow application for all organization.

**Comment by ThibaultBC** [comment]
ADMS part is done. Still requires a code modification.

**Comment by harsimranmaan** [comment]
https://github.com/Azure/ipam/issues/261
