### ISSUE TITLE
Azure Sample Application - Serverless

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#85]
Create a sample application that uses [Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-overview), as a reference example of how-to create the required infrastructure, and deploy a serverless application into that environment.

Resources may include:
- Azure Functions
- Azure App Service Plan
- Other resources TBD

## Acceptance Criteria
- [X] **Scenario: Function App Infrastructure**
  - An Azure Function, and Azure App Service Plan are deployed in the same Resource Group
  - Required configurations/properties are either hard-coded, or set using variables
- [X] **Scenario: Deployment of the sample application onto the infrastructure**
  - Utilizing the infrastructure that was deployed, build/push serverless application code to the Azure Function

**Comment by AErmie** [comment]
The latest iteration of the code (currently in the [terraform-code-refactor](https://github.com/bcgov-c/ecf-azure-startup-sample-app-serverless/tree/terraform-code-refactor) branch), deploys the infrastructure components through a separate [Deploy Infrastructure pipeline](https://github.com/bcgov-c/ecf-azure-startup-sample-app-serverless/actions/workflows/deploy-infra.yml).

Application-level code modifications were required, to successfully build/compile the Client component. Currently, both the Server (backend), and Client (frontend) components are building/compiling successfully. These are also able to successfully be deployed onto the target infrastructure, using a dedicated [Deploy Application pipeline](https://github.com/bcgov-c/ecf-azure-startup-sample-app-serverless/actions/workflows/deploy-app.yml).

However, the application itself has some issues, not limited to:
- Having hard-coded backend endpoints
- Permissions issues (requiring CORS to be configured on the API Management infrastructure

**Comment by AErmie** [comment]
Merged latest "working" code example into the `main` branch

> Note: Additional work will now be done on securing the infrastructure (ie. using VNets/Subnets, Private Endpoints, etc.)
> Additionally, the sample application code may be changed/updated per @wrnu

**Comment by AErmie** [comment]
Additional enhancements (ie. "secure" infrastructure), will be tracked in a new Issue
